#!/usr/bin/perl
# Create the documentation for the Mime::Types distribution.
# This script can be called as part of the mkdist procedure, but also
# on its own.

use warnings;
use strict;

use lib '../OODoc/lib';  # the next release of OODoc software ;-)

use OODoc;

my $verbose      = $ARGV[0] || 0;

##### Synchronize these constants with the mkdist script.
my $workdir      = '/tmp/GeoProj4';

##### Other constants
my $distribution = 'Geo::Proj4';
my $name         = 'Proj4 library';

my $pod_format   = 'pod2';         # install Bundle::Text::MagicTemplate first

#
# The OODoc object is created.  It is used to collect all the manual
# information in.
#

my $doc  = OODoc->new
 ( distribution  => $name
 , verbose       => $verbose
 );

my $version      = $doc->version;
print "*** Producing $distribution version $version\n" if $verbose;

#
# Reading all the manual pages
# This could be called more than once to combine different sets of
# manual pages in different formats.
#

print "* Processing files\n" if $verbose;
$doc->processFiles(workdir => $workdir);

#
# Prepare the collected information
# Expanding the inheritance relations and such, to simplify the
# production of manual pages in their different formats.
#

print "* Preparation phase\n" if $verbose;
$doc->prepare;

#
# Create POD
# Produce manual pages in the usual Perl style.
#

print "* Creating POD\n" if $verbose;

$doc->create
  ( $pod_format
  , workdir => $workdir
  , append => <<TEXT);

=head1 COPYRIGHTS

Module version $version.
Developed and maintained by Mark Overmeer E<lt>proj4\@overmeer.netE<gt>.

Originally Written by Schuyler Erle E<lt>schuyler\@nocat.netE<gt> and
Rich Gibson E<lt>rich\@nocat.netE<gt>.  Their site: Mapping Hacks home
page: L<http://www.mappinghacks.com>

Copyright (c) 2004-2005 by the author(s). All rights reserved.

=head1 LICENSE
                                                                                
This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.3 or,
at your option, any later version of Perl 5 you may have available.
TEXT
